import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
				<main className="w-[768px] mx-auto">
				{/* <header className="flex gap-[10px]">
					<Link href={`/`}>index</Link>
					<Link href={`/search`}>search</Link>
					<Link href={`/book/1`}>book</Link>
				</header> */}
        {children}
				</main>
      </body>
    </html>
  );
}
